"""Dependency-light OMOP domain routing shared by source and retrieval adapters."""


TARGETS = {
    "condition_occurrence": {
        "collection": "snomed_conditions",
        "vocabulary": "SNOMED",
        "domain": "Condition",
        "source_vocabulary": "CMF_SYNTHEA_CONDITION",
        "id_column": "condition_occurrence_id",
        "concept_column": "condition_concept_id",
        "source_concept_column": "condition_source_concept_id",
        "source_column": "condition_source_value",
    },
    "drug_exposure": {
        "collection": "rxnorm_drugs",
        "vocabulary": "RxNorm",
        "domain": "Drug",
        "source_vocabulary": "CMF_SYNTHEA_DRUG",
        "id_column": "drug_exposure_id",
        "concept_column": "drug_concept_id",
        "source_concept_column": "drug_source_concept_id",
        "source_column": "drug_source_value",
    },
    "measurement": {
        "collection": "loinc_measurements",
        "vocabulary": "LOINC",
        "domain": "Measurement",
        "source_vocabulary": "CMF_SYNTHEA_MEASUREMENT",
        "id_column": "measurement_id",
        "concept_column": "measurement_concept_id",
        "source_concept_column": "measurement_source_concept_id",
        "source_column": "measurement_source_value",
    },
    "procedure_occurrence": {
        "collection": "snomed_procedures",
        "vocabulary": "SNOMED",
        "domain": "Procedure",
        "source_vocabulary": "CMF_SYNTHEA_PROCEDURE",
        "id_column": "procedure_occurrence_id",
        "concept_column": "procedure_concept_id",
        "source_concept_column": "procedure_source_concept_id",
        "source_column": "procedure_source_value",
    },
    "observation": {
        "collection": "standard_observations",
        "vocabulary": "SNOMED+LOINC",
        "vocabularies": ("SNOMED", "LOINC"),
        "domain": "Observation",
        "source_vocabulary": "CMF_SYNTHEA_OBSERVATION",
        "id_column": "observation_id",
        "concept_column": "observation_concept_id",
        "source_concept_column": "observation_source_concept_id",
        "source_column": "observation_source_value",
    },
    "device_exposure": {
        "collection": "snomed_devices",
        "vocabulary": "SNOMED",
        "domain": "Device",
        "source_vocabulary": "CMF_SYNTHEA_DEVICE",
        "id_column": "device_exposure_id",
        "concept_column": "device_concept_id",
        "source_concept_column": "device_source_concept_id",
        "source_column": "device_source_value",
    },
}
